import webapp2
from google.appengine.ext import ndb

class WOTD(ndb.Model):
	daystamp = ndb.IntegerProperty()
	word = ndb.StringProperty()
	definition = ndb.StringProperty()

class UploadWOTD(webapp2.RequestHandler):
	def get(self):
		WOTD(daystamp=0, word='Masticator', definition='A type of glue that does not crack or break when it is bent.').put()
		WOTD(daystamp=1, word='Vitals', definition='Vital signs.').put()
		WOTD(daystamp=2, word='Venerate', definition='Passed from one person to another during sex.').put()
		WOTD(daystamp=3, word='Neaten', definition='To make something neater and more organized.').put()
		WOTD(daystamp=4, word='Feministic', definition='Someone who supports the idea that women should have the same rights and opportunities as men.').put()
		WOTD(daystamp=5, word='Airplane', definition='A vehicle that flies by using wings and one or more engines.').put()
		WOTD(daystamp=6, word='Promulged', definition='To spread an idea or belief to as many people as possible.').put()
		WOTD(daystamp=7, word='Minuter', definition='Extremely small.').put()
		WOTD(daystamp=8, word='Quiting', definition='Very, but not extremely.').put()
		WOTD(daystamp=9, word='Shirk', definition='To deliberately avoid doing something you should do, because you are lazy.').put()
		WOTD(daystamp=10, word='Sniggerers', definition='Snicker.').put()
		WOTD(daystamp=11, word='Polytheism', definition='The belief that there is more than one god.').put()
		WOTD(daystamp=12, word='Adaptable', definition='A movie or play that was first written in a different form, for example as a book.').put()
		WOTD(daystamp=13, word='Lavish', definition='To give someone a lot of something such as expensive presents, love, or praise.').put()
		WOTD(daystamp=14, word='Mealed', definition='An occasion when you eat food, for example breakfast or dinner, or the food that you eat on that occasion.').put()
		WOTD(daystamp=15, word='Obstetric', definition='The part of medical science that deals with the birth of children.').put()
		WOTD(daystamp=16, word='Outvoting', definition='To defeat someone or something by having a larger number of votes.').put()
		WOTD(daystamp=17, word='Cohesible', definition='The quality a group of people, a set of ideas, etc. has when all the parts or members of it are connected or related in a reasonable way to form a whole.').put()
		WOTD(daystamp=18, word='Elections', definition='The person who has been elected as president, etc., but who has not yet officially started his or her job.').put()
		WOTD(daystamp=19, word='Singings', definition='To produce musical sounds, songs, etc. with your voice.').put()
		WOTD(daystamp=20, word='Apoplexy', definition='An illness caused by a problem in your brain that can damage your ability to move, feel, or think.').put()
		WOTD(daystamp=21, word='Anionic', definition='An ionatom or group of atoms with an electrical charge with a negative electrical charge that is attracted to the anode inside a battery, electrolytic cell, etc.').put()
		WOTD(daystamp=22, word='Sutures', definition='The act of sewing a wound together, or a stitch used to do this.').put()
		WOTD(daystamp=23, word='Skid', definition='A sudden sliding movement of a vehicle, that you cannot control.').put()
		WOTD(daystamp=24, word='Muffineers', definition='A small slightly sweet type of bread that often has fruit in it.').put()
		WOTD(daystamp=25, word='Hurtful', definition='Suffering pain or injury.').put()
		WOTD(daystamp=26, word='Err', definition='To be more careful, safe, etc. than is necessary rather than risk making a mistake.').put()
		WOTD(daystamp=27, word='Tamoxifen', definition='A drug that is used to treat breast cancer.').put()
		WOTD(daystamp=28, word='Unisex', definition='Intended for both men and women.').put()
		WOTD(daystamp=29, word='Melled', definition='Running or moving in a fast uncontrolled way.').put()
		WOTD(daystamp=30, word='Backroom', definition='Backroom deals, politics, etc. happen in a private or secret way, when they should happen in public.').put()
		WOTD(daystamp=31, word='Sputnik', definition='An early Soviet satellite. “Sputnik 1” was the first artificial satellite that went around the Earth, in 1957.').put()
		WOTD(daystamp=32, word='Drummer', definition='Someone who plays drums.').put()
		WOTD(daystamp=33, word='Reclaimers', definition='To get back something that once belonged to you.').put()
		WOTD(daystamp=34, word='Updated', definition='To add the most recent information to something.').put()
		WOTD(daystamp=35, word='Simulating', definition='A machine that is used for training people by letting them feel what real conditions are like, for example in a plane.').put()
		WOTD(daystamp=36, word='Whiningly', definition='To complain in a sad annoying voice about something.').put()
		WOTD(daystamp=37, word='Telescopic', definition='Made of parts that slide over each other so that the whole thing can be made longer or shorter.').put()
		WOTD(daystamp=38, word='Leftover', definition='Remaining after all the rest has been used, eaten, etc.').put()
		WOTD(daystamp=39, word='Weather', definition='To come through a very difficult situation safely.').put()
		WOTD(daystamp=40, word='Enters', definition='A painful condition that affects your intestines.').put()
		WOTD(daystamp=41, word='Skimming', definition='To remove something from the surface of a liquid, especially floating oil or solids.').put()
		WOTD(daystamp=42, word='Chaplet', definition='A band of flowers worn on the head.').put()
		WOTD(daystamp=43, word='Mated', definition='If animals mate, they have sex to produce babies.').put()
		WOTD(daystamp=44, word='Renderable', definition='To cause someone or something to be in a particular condition.').put()
		WOTD(daystamp=45, word='Deformedly', definition='Part of someone’s body that is not the normal shape, or the condition of having such a body part.').put()
		WOTD(daystamp=46, word='Beatifies', definition='If the Catholic Church beatifies someone who has died, it says officially that he or she is a holy or special person as a first step to becoming a saint.').put()
		WOTD(daystamp=47, word='Minglingly', definition='If two or more feelings, sounds, smells, etc. mingle or are mingled, they combine with each other.').put()
		WOTD(daystamp=48, word='Magging', definition='A magazine.').put()
		WOTD(daystamp=49, word='Wicker', definition='Made from thin dried tree branches woven together.').put()
		WOTD(daystamp=50, word='Pasture', definition='A field or area of land that is covered with grass, which cattle, sheep, etc. eat.').put()
		WOTD(daystamp=51, word='Croupe', definition='An illness in children which makes them cough and have difficulty breathing.').put()
		WOTD(daystamp=52, word='Mower', definition='A machine or tool used for cutting grass.').put()
		WOTD(daystamp=53, word='Conflation', definition='To combine two or more things to form a single new thing, whether it is correct or not.').put()
		WOTD(daystamp=54, word='Monotreme', definition='A type of animal that passes the waste from its body through the same opening it uses to lay its eggs. A platypus is an example of a monotreme.').put()
		WOTD(daystamp=55, word='Thirded', definition='Rd; next after the second.').put()
		WOTD(daystamp=56, word='Corked', definition='Corked wine tastes bad because a decaying cork has allowed air into the bottle.').put()
		WOTD(daystamp=57, word='Consols', definition='To make someone feel better when he or she is feeling sad or disappointed.').put()
		WOTD(daystamp=58, word='Warrant', definition='A legal document signed by a judge, giving the police permission to take a particular action, for example to arrest someone or to search a building.').put()
		WOTD(daystamp=59, word='Vacuous', definition='Lacking in serious thought or intelligence.').put()
		WOTD(daystamp=60, word='Colonic', definition='The lower part of the intestines, in which food is changed into waste matter.').put()
		WOTD(daystamp=61, word='Impresario', definition='Someone who organizes performances in theaters, concert halls, etc.').put()
		WOTD(daystamp=62, word='Imagine', definition='Able to be imagined.').put()
		WOTD(daystamp=63, word='Babe', definition='A way of speaking to someone you love, especially your wife, husband, boyfriend, or girlfriend.').put()
		WOTD(daystamp=64, word='Punished', definition='A punishable action may be punished by law, especially in a particular way.').put()
		WOTD(daystamp=65, word='Consults', definition='The service of providing information, advice, and training to companies.').put()
		WOTD(daystamp=66, word='Candida', definition='A yeast infection.').put()
		WOTD(daystamp=67, word='Tassels', definition='A large number of threads tied together into a round ball at one end and hung as a decoration on clothes, curtains, etc.').put()
		WOTD(daystamp=68, word='Tailback', definition='The player who is the farthest back from the front line in football, and who often runs with the ball.').put()
		WOTD(daystamp=69, word='Bustled', definition='Busy and usually noisy activity.').put()
		WOTD(daystamp=70, word='Rabis', definition='A disease that kills animals and people, that you can get if you are bitten by an infected animal.').put()
		WOTD(daystamp=71, word='Overhear', definition='To accidentally hear what other people are saying, when they do not know that you have heard.').put()
		WOTD(daystamp=72, word='Careering', definition='A job or series of related jobs that you have been trained for and intend to do for a long period of your life.').put()
		WOTD(daystamp=73, word='Tympan', definition='The eardrum or a similar part in animals or insects.').put()
		WOTD(daystamp=74, word='Overs', definition='Falling down from an upright position.').put()
		WOTD(daystamp=75, word='Glean', definition='Small pieces of information that you have found out, even though it was difficult.').put()
		WOTD(daystamp=76, word='Advanced', definition='Progress or development in your job, level of knowledge, etc.').put()
		WOTD(daystamp=77, word='Flues', definition='A pipe through which smoke or heat from a fire can pass out of a building.').put()
		WOTD(daystamp=78, word='Colliding', definition='To crash violently into something or someone.').put()
		WOTD(daystamp=79, word='Biliously', definition='Feeling sick to your stomach.').put()
		WOTD(daystamp=80, word='Subjects', definition='A subjective statement, report, attitude, etc. is influenced by personal opinion and can therefore be unfair.').put()
		WOTD(daystamp=81, word='Virile', definition='Having or showing traditionally male qualities such as strength, courage, and sexual attractiveness.').put()
		WOTD(daystamp=82, word='Privet', definition='A bush with leaves that stay green all year, often grown to form a hedge.').put()
		WOTD(daystamp=83, word='Noisome', definition='Extremely bad, ugly, etc.').put()
		WOTD(daystamp=84, word='Purrs', definition='If a cat purrs, it makes a soft, low sound in its throat to show that it is pleased.').put()
		WOTD(daystamp=85, word='Flatness', definition='In a straight position or stretched against a flat surface.').put()
		WOTD(daystamp=86, word='Sunbed', definition='A metal structure the size of a bed, that you lie on to make your skin brown using light from special lamps.').put()
		WOTD(daystamp=87, word='Spectator', definition='Someone who is watching an event or game.').put()
		WOTD(daystamp=88, word='Figment', definition='Something that you imagine to be real, but does not exist.').put()
		WOTD(daystamp=89, word='Libates', definition='An alcoholic drink.').put()
		WOTD(daystamp=90, word='Tikes', definition='Another spelling of tyke.').put()
		WOTD(daystamp=91, word='Stenches', definition='A very strong bad smell.').put()
		WOTD(daystamp=92, word='Gen', definition='The written abbreviation of general.').put()
		WOTD(daystamp=93, word='Adjunction', definition='Connected to something else, but not completely a part of it.').put()
		WOTD(daystamp=94, word='Damnations', definition='The act of punishing someone by sending him or her to hell forever after they die, or the state of being in hell forever.').put()
		WOTD(daystamp=95, word='Miscarry', definition='To give birth to a baby too early for it to live.').put()
		WOTD(daystamp=96, word='Bylaws', definition='A rule made by an organization to control the people who belong to it.').put()
		WOTD(daystamp=97, word='Endangers', definition='To put someone or something in a dangerous situation.').put()
		WOTD(daystamp=98, word='Worsens', definition='To become worse, or to make something worse.').put()
		WOTD(daystamp=99, word='Shippings', definition='The price charged for delivering goods.').put()
		WOTD(daystamp=100, word='Inborn', definition='An inborn quality or ability is one that you have had naturally since birth.').put()


app = webapp2.WSGIApplication([
	('/wotd_uploader/?', UploadWOTD),
], debug=True)