runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /wotd_uploader/.*
  script: /wotd_uploader/wotd_uploader.app

libraries:
- name: webapp2
  version: latest
- name: markupsafe
  version: "0.15"
